#!/bin/bash

# Create the .mo files
for i in `ls check/locale`; do
  if [[ $i != "en" ]]; then
    cd "check/locale/$i/LC_MESSAGES"
    if [[ ! -e messages.po ]]; then
      cd -
      rm -r "check/locale/$i"
    else
      sed -i "" "s/ <.*@.*\..*>//" ./messages.po
      msgfmt -c messages.po
      cd -
    fi
  fi
done
