<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Contao Check <?php echo CONTAO_CHECK_VERSION ?></title>
  <link rel="stylesheet" href="assets/style.css">
</head>
<body>
<div id="wrapper">
  <h1>Contao Check <?php echo CONTAO_CHECK_VERSION ?></h1>
  <div class="row">
    <h2><?php echo _('Contao 3.x') ?></h2>
  </div>
  <div class="row">
    <h3><?php printf(_('PHP %s or greater'), static::PHP_VERSION) ?></h3>
    <?php if ($this->hasPhp()): ?>
      <p class="confirm"><?php printf(_('You have PHP version %s.'), phpversion()) ?></p>
    <?php else: ?>
      <p class="error"><?php printf(_('You have PHP version %s.'), phpversion()) ?></p>
      <p class="explain"><?php printf(_('As of Contao 3.4 you need at least PHP %s.'), static::PHP_VERSION) ?></p>
    <?php endif; ?>
  </div>
  <div class="row">
    <h3><?php echo _('PHP GDlib extension') ?></h3>
    <?php if ($this->hasGd()): ?>
      <p class="confirm"><?php echo _('The PHP GDlib extension is enabled.') ?></p>
    <?php else: ?>
      <p class="error"><?php echo _('The PHP GDlib extension is not enabled.') ?></p>
      <p class="explain"><?php echo _('The PHP GDlib extension is not part of the PHP core and has to be explicitly enabled using the --with-gd flag. Recompile PHP with the flag.') ?></p>
    <?php endif; ?>
  </div>
  <div class="row">
    <h3><?php echo _('PHP DOM extension') ?></h3>
    <?php if ($this->hasGd()): ?>
      <p class="confirm"><?php echo _('The PHP DOM extension is enabled.') ?></p>
    <?php else: ?>
      <p class="error"><?php echo _('The PHP DOM extension is not enabled.') ?></p>
      <p class="explain"><?php echo _('The PHP DOM extension is part of the PHP core and has to be explicitly disabled using the --disable-dom flag. Recompile PHP without the flag.') ?></p>
    <?php endif; ?>
  </div>
  <div class="row">
    <?php if ($this->isCompatible()): ?>
      <p class="confirm large"><?php echo _('You can install Contao 3.x on this server.') ?></p>
    <?php else: ?>
      <p class="error large"><?php echo _('You cannot install Contao 3.x on this server.') ?></p>
    <?php endif; ?>
  </div>
  <p class="back"><a href="./"><?php echo _('Go back') ?></a></p>
</div>
</body>
</html>