<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Contao Check <?php echo CONTAO_CHECK_VERSION ?></title>
  <link rel="stylesheet" href="assets/style.css">
  <meta name="robots" content="noindex, nofollow">
</head>
<body>
<div id="wrapper">
  <h1>Contao Check <?php echo CONTAO_CHECK_VERSION ?></h1>
  <div class="row">
    <h2><?php echo __('Contao 2.x') ?></h2>
  </div>
  <div class="row">
    <h3><?php printf(__('PHP %s or greater'), static::PHP_VERSION) ?></h3>
    <?php if ($this->hasPhp()): ?>
      <p class="confirm"><?php printf(__('You have PHP version %s.'), phpversion()) ?></p>
    <?php else: ?>
      <p class="error"><?php printf(__('You have PHP version %s.'), phpversion()) ?></p>
      <p class="explain"><?php printf(__('You need at least PHP %s.'), static::PHP_VERSION) ?></p>
    <?php endif; ?>
  </div>
  <div class="row">
    <h3><?php echo __('PHP 7.x') ?></h3>
    <?php if ($this->hasNotPhp7()): ?>
      <p class="confirm"><?php printf(__('The PHP version is lower than 7.0.0.'), phpversion()) ?></p>
    <?php else: ?>
      <p class="error"><?php printf(__('You have PHP version %s.'), phpversion()) ?></p>
      <p class="explain"><?php printf(__('Contao 2.x is incompatible with PHP 7.'), static::PHP_VERSION) ?></p>
    <?php endif; ?>
  </div>
  <div class="row">
    <h3><?php echo __('PHP GDlib extension') ?></h3>
    <?php if ($this->hasGd()): ?>
      <p class="confirm"><?php echo __('The PHP GDlib extension is enabled.') ?></p>
    <?php else: ?>
      <p class="error"><?php echo __('The PHP GDlib extension is not enabled.') ?></p>
      <p class="explain"><?php echo __('The PHP GDlib extension is not part of the PHP core and has to be explicitly enabled using the --with-gd flag. Recompile PHP with the flag.') ?></p>
    <?php endif; ?>
  </div>
  <div class="row">
    <h3><?php echo __('PHP DOM extension') ?></h3>
    <?php if ($this->hasDom()): ?>
      <p class="confirm"><?php echo __('The PHP DOM extension is enabled.') ?></p>
    <?php else: ?>
      <p class="error"><?php echo __('The PHP DOM extension is not enabled.') ?></p>
      <p class="explain"><?php echo __('The PHP DOM extension is part of the PHP core and has to be explicitly disabled using the --disable-dom flag. Recompile PHP without the flag.') ?></p>
    <?php endif; ?>
  </div>
  <div class="row">
    <?php if ($this->isCompatible()): ?>
      <p class="confirm large"><?php echo __('You can install Contao 2.x on this server.') ?></p>
    <?php else: ?>
      <p class="error large"><?php echo __('You cannot install Contao 2.x on this server.') ?></p>
    <?php endif; ?>
  </div>
  <p class="back"><a href="./"><?php echo __('Go back') ?></a></p>
</div>
</body>
</html>