<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Contao Check <?php echo CONTAO_CHECK_VERSION ?></title>
  <link rel="stylesheet" href="assets/style.css">
</head>
<body>
<div id="wrapper">
  <h1>Contao Check <?php echo CONTAO_CHECK_VERSION ?></h1>
  <div class="row">
    <h2><?php echo __('Installation') ?></h2>
  </div>
  <div class="row">
    <h3><?php echo __('Web installer') ?></h3>
    <?php if ($this->hasInstallation()): ?>
      <p class="error"><?php printf(__('There is a Contao installation already. Are you looking for the %s?'), '<a href="https://update.contao.org" target="_blank">Live Update</a>') ?></p>
    <?php elseif ($this->requiresFtp()): ?>
      <p class="error"><?php echo __('The automatic installation is not possible on your server due to safe_mode or file permission restrictions.') ?></p>
    <?php elseif ($this->isAvailable()): ?>
      <p class="confirm"><?php echo __('The automatic installation is possible on your server.') ?></p>
    <?php else: ?>
      <p class="error"><?php echo __('The automatic installation is not possible on your server.') ?></p>
      <p class="explain"><?php echo __('Your PHP installation either cannot connect to download.contao.org or is missing the PHP extension cURL or Zip.') ?></p>
    <?php endif; ?>
  </div>
  <?php if (!$this->hasInstallation() && !$this->requiresFtp()): ?>
    <div class="row">
      <?php if (!$this->isAvailable()): ?>
        <h3><?php echo __('Manual installation') ?></h3>
        <ul>
          <li><?php printf(__('Go to %s and download the latest Contao version.'), '<a href="https://contao.org/download.html">contao.org</a>') ?></li>
          <li><?php echo __('Extract the download archive and upload the files to your server using an (S)FTP client.') ?></li>
          <li><?php echo __('Open the Contao install tool by adding "/contao/install.php" to the URL of your installation.') ?></li>
        </ul>
      <?php elseif (!isset($_POST['version'])): ?>
        <?php if ($this->lts_version): ?>
          <h3><?php echo __('Target version') ?></h3>
          <form method="post">
            <div class="versions">
              <select name="version" class="select">
                <option value="<?php echo $this->lts_version; ?>"><?php echo $this->lts_version; ?> (LTS)</option>
              </select>
            </div>
            <p class="mt"><input class="button orange" type="submit" value="<?php echo __('Start the installation') ?>"></p>
          </form>
        <?php elseif ($this->message): ?>
          <h3><?php echo __('Target version') ?></h3>
          <p class="error"><?php echo $this->message ?>.</p>
        <?php else: ?>
          <h3><?php echo __('Target version') ?></h3>
          <p class="error"><?php echo __('An unknown error occurred while getting the newest LTS version.') ?></p>
        <?php endif; ?>
      <?php else: ?>
        <?php if ($this->message): ?>
          <h3><?php echo __('Installation failed') ?></h3>
          <p class="error"><?php echo $this->message ?>.</p>
        <?php else: ?>
          <h3><?php echo __('Installation complete') ?></h3>
          <p class="confirm"><?php printf(__('Contao %s has been installed in %s.'), filter_var($_POST['version'], FILTER_SANITIZE_STRING), dirname(dirname(dirname(__FILE__)))) ?></p>
          <p class="mt"><a href="../contao/install.php" class="button orange"><?php echo __('Open the Contao install tool') ?></a></p>
        <?php endif; ?>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <p class="back"><a href="./"><?php echo __('Go back') ?></a></p>
</div>
<script src="assets/script.js"></script>
</body>
</html>